/**
 * Created by guangqiang on 2017/8/22.
 */

/**
 * action对象的type属性集合
 */
const actionType = {

  FETCH_LOADING_SUFFIX : '_LOADING',
  FETCH_SUCCESS_SUFFIX : '_SUCCESS',
  FETCH_ERROR_SUFFIX : '_ERROR',
  FETCH_SHOW_HUD: 'FETCH_SHOW_HUD',

  // router
  REACT_NATIVE_ROUTER_FLUX_EVENT: 'REACT_NATIVE_ROUTER_FLUX_EVENT',
  REACT_NATIVE_ROUTER_FLUX_EVENT_CLEAR: 'REACT_NATIVE_ROUTER_FLUX_EVENT_CLEAR',
  REACT_NATIVE_ROUTER_FLUX_BACK: 'Navigation/BACK',
  REACT_NATIVE_ROUTER_FLUX_BLUR: 'REACT_NATIVE_ROUTER_FLUX_BLUR',
  REACT_NATIVE_ROUTER_FLUX_FOCUS: 'REACT_NATIVE_ROUTER_FLUX_FOCUS',
  REACT_NATIVE_ROUTER_FLUX_REPLACE: 'REACT_NATIVE_ROUTER_FLUX_REPLACE',
  REACT_NATIVE_ROUTER_FLUX_SET_PARAMS: 'Navigation/SET_PARAMS',

  MAIN_LOGIN_INFO:'LOGIN_INFO',
}

export default actionType