# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source ‘https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git’

platform :ios, '9.0'
target 'RNProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for RNProject

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
	  'Core',
	  'ART',
	  'CxxBridge',
      'DevSupport',
	  'RCTActionSheet',
	  'RCTGeolocation',
	  'RCTImage',
	  'RCTNetwork',
	  'RCTPushNotification',
	  'RCTSettings',
	  'RCTText',
	  'RCTVibration',
	  'RCTWebSocket',
	  'RCTLinkingIOS',
	  'RCTAnimation',
	]

  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'																												
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'react-native-baidumap-sdk', :podspec => '../node_modules/react-native-baidumap-sdk/lib/ios/react-native-baidumap-sdk.podspec'
  pod 'react-native-orientation', :podspec => '../node_modules/react-native-orientation/react-native-orientation.podspec'
  pod 'react-native-video', :podspec => '../node_modules/react-native-video/react-native-video.podspec'
  pod 'react-native-blur', :podspec => '../node_modules/react-native-blur/react-native-blur.podspec'
  pod 'CodePush', :podspec => '../node_modules/react-native-code-push/CodePush.podspec'
  pod 'react-native-fast-image', :podspec => '../node_modules/react-native-fast-image/react-native-fast-image.podspec'
  pod 'RNGestureHandler', :podspec => '../node_modules/react-native-gesture-handler/RNGestureHandler.podspec'
  pod 'RNVectorIcons', :podspec => '../node_modules/react-native-vector-icons/RNVectorIcons.podspec'


  def change_lines_in_file(file_path, &change)
	  print "Fixing #{file_path}...\n"

	  contents = []

	  file = File.open(file_path, 'r')
	  file.each_line do | line |
	    contents << line
	  end
	  file.close

	  File.open(file_path, 'w') do |f|
	    f.puts(change.call(contents))
	  end
	end


post_install do |installer|
  # https://github.com/facebook/yoga/issues/711#issuecomment-381098373
  change_lines_in_file('./Pods/Target Support Files/yoga/yoga-umbrella.h') do |lines|
    lines.reject do | line |
      [
        '#import "Utils.h"',
        '#import "YGLayout.h"',
        '#import "YGNode.h"',
        '#import "YGNodePrint.h"',
        '#import "YGStyle.h"',
        '#import "Yoga-internal.h"',
      ].include?(line.strip)
    end
  end

  # https://github.com/facebook/yoga/issues/711#issuecomment-374605785
  change_lines_in_file('../node_modules/react-native/React/Base/Surface/SurfaceHostingView/RCTSurfaceSizeMeasureMode.h') do |lines|
    unless lines[27].include?("#ifdef __cplusplus")
      lines.insert(27, "#ifdef __cplusplus")
      lines.insert(34, "#endif")
    end
    lines
  end

  # https://github.com/facebook/react-native/issues/13198
  change_lines_in_file('../node_modules/react-native/Libraries/NativeAnimation/RCTNativeAnimatedNodesManager.h') do |lines|
    lines.map { |line| line.include?("#import <RCTAnimation/RCTValueAnimatedNode.h>") ? '#import "RCTValueAnimatedNode.h"' : line }
  end

  # https://github.com/facebook/react-native/issues/16039
  change_lines_in_file('../node_modules/react-native/Libraries/WebSocket/RCTReconnectingWebSocket.m') do |lines|
    lines.map { |line| line.include?("#import <fishhook/fishhook.h>") ? '#import "fishhook.h"' : line }
  end
end
end
